### PR TITLE
🐛 Remove non-existing branch from scheduled actions

### PR DESCRIPTION
**Pull request by weseven**
**What this PR does / why we need it**:
Removes non-existing branches causing fails to scheduled github actions.
Keep only release-1.4 for the default branch.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
towards https://github.com/giantswarm/roadmap/issues/2787

### CODE REVIEW

**Comment by AndiDog** [comment]
You need to assign reviewers

**Comment by AndiDog** [comment]
At best, we cut out the upstream stuff completely. For example, own fork PRs show as failing because of check `verify / verify PR contents (pull_request_target)` (which we don't care about).

And please adapt our custom README to display which files are expected to differ from upstream.

**Review by njuettner — APPROVED** [review]
lgtm 👍🏻

**Comment by weseven** [comment]
Thanks for the feedback!
I've updated the README and added a commit removing the verify actions, and I think we also need to remove the workflow runs to completely disable it. 
I'm not sure though if that will compromise the ability to merge the current two PRs, if someone has experience with github action I'd like their opinion on how to proceed as I'm not that familiar with them :)

**Pull request merged**
